// @vitest-environment node
import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import manifest from "@/app/manifest";
import { decodePng } from "@/test/png";

const root = process.cwd();
const app = path.join(root, "src/app");

/**
 * The icon set, V4 item 6.2 (Q38–Q40, Q436).
 *
 * Every file here is generated by `scripts/render-icons.mjs` from one drawing. These are the
 * assertions that catch the two ways that goes wrong: a file that stops being regenerated and
 * quietly drifts away from the mark, and a file that was never generated at all — which is what
 * `favicon.ico` was until today, a 25,931-byte leftover from the day the repo was created that
 * no script in this project had ever written.
 */
describe("the favicon", () => {
  it("is an SVG, so it can answer light and dark differently", () => {
    // The whole reason Q38 asked for the format change. A tab strip has no theme attribute to
    // read — the page has not been parsed — so the only way the icon can match the browser is a
    // media query inside the image itself. `.ico` cannot carry one.
    const svg = fs.readFileSync(path.join(app, "icon.svg"), "utf8");
    expect(svg).toContain("prefers-color-scheme: light");
    expect(svg).toContain("currentColor");
  });

  it("names two different colours, one per scheme", () => {
    const svg = fs.readFileSync(path.join(app, "icon.svg"), "utf8");
    const colours = [...svg.matchAll(/color:\s*(#[0-9a-f]{6})/gi)].map((m) => m[1].toLowerCase());
    expect(colours).toHaveLength(2);
    expect(new Set(colours).size).toBe(2);
  });

  it("still ships an .ico, because browsers ask for one whether or not it is linked", () => {
    const ico = fs.readFileSync(path.join(app, "favicon.ico"));
    expect(ico.readUInt16LE(0)).toBe(0); // reserved
    expect(ico.readUInt16LE(2)).toBe(1); // 1 = icon, not cursor
    expect(ico.readUInt16LE(4)).toBe(3); // 16, 32, 48
  });

  it("carries a real 16px frame, which is the size the mark was designed against", () => {
    // Q33 made 16px the primary constraint. An .ico whose smallest frame is 32 or 48 leaves the
    // browser to downscale, which is where the folds turn to grey mush.
    const ico = fs.readFileSync(path.join(app, "favicon.ico"));
    const sizes = [0, 1, 2].map((i) => ico[6 + i * 16] || 256);
    expect(sizes).toContain(16);
  });

  it("is not the file that was there before", () => {
    // Narrow and deliberate. The old one was 25,931 bytes of something this project never drew;
    // three PNG frames of a two-colour mark are an order of magnitude smaller. If this ever
    // fails, someone has restored a stock favicon over the generated one.
    const ico = fs.readFileSync(path.join(app, "favicon.ico"));
    expect(ico.length).toBeLessThan(20_000);
  });
});

describe("the shortcut icons", () => {
  const shortcuts = manifest().shortcuts ?? [];

  it("gives every launcher shortcut an icon of its own (Q436)", () => {
    // They all pointed at `icon-192.png` before, so a long-press showed the app icon three times
    // and the menu carried no information beyond its labels.
    const used = shortcuts.map((s) => s.icons?.[0]?.src);
    expect(used).toHaveLength(3);
    expect(new Set(used).size).toBe(3);
    expect(used).not.toContain("/icons/icon-192.png");
  });

  it("ships every file the manifest names", () => {
    // A manifest naming a missing icon does not fail a build and does not fail a page load. It
    // shows up as a blank square in a long-press menu, on one device, months later.
    for (const shortcut of shortcuts) {
      const src = shortcut.icons?.[0]?.src;
      expect(src, `${shortcut.name} has no icon`).toBeTruthy();
      expect(fs.existsSync(path.join(root, "public", src!)), `${src} missing`).toBe(true);
    }
  });

  it("draws them on the same tile as the app icon", () => {
    // Consistency the eye checks and no other test would: a shortcut glyph on a transparent or
    // differently-coloured ground reads as a foreign icon sitting in Victor's menu.
    //
    // Sampled at the middle of the top edge, not at (0,0): the tile is `rx="96"`, so the literal
    // corner pixel is outside the rounded rect and correctly transparent. Reading it and
    // demanding opacity is how this test failed the first time it ran, on a file that was right.
    for (const shortcut of shortcuts) {
      const png = decodePng(fs.readFileSync(path.join(root, "public", shortcut.icons![0].src)));
      const i = (2 * png.width + Math.floor(png.width / 2)) * 4;
      const [r, g, b, a] = png.pixels.slice(i, i + 4);
      expect(a).toBe(255);
      expect(Math.max(r, g, b)).toBeLessThan(40);
    }
  });
});

describe("the Apple touch icon", () => {
  it("exists, is 180 square, and carries no alpha channel at all", () => {
    // iOS ignores the manifest entirely and composites any transparency onto white, so this one
    // keeps its tile where `icon.svg` drops it. A transparent apple-touch-icon is how a dark
    // mark ends up as a dark smear on a white square on someone's home screen.
    //
    // Asserted on the PNG colour type rather than on a pixel, which is a stronger statement than
    // the one first written here: an encoder only drops to type 2 (RGB) when *every* pixel is
    // opaque, so this checks the whole image rather than the one pixel that got sampled.
    const png = fs.readFileSync(path.join(app, "apple-icon.png"));
    expect(png.subarray(12, 16).toString("ascii")).toBe("IHDR");
    expect(png.readUInt32BE(16)).toBe(180);
    expect(png.readUInt32BE(20)).toBe(180);
    expect(png[25]).toBe(2); // colour type 2 = RGB, no alpha
  });
});
