CREATE TABLE "exercises" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"modality" text DEFAULT 'lift' NOT NULL,
	"muscles" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"equipment" text DEFAULT '' NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"client_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"updated_hlc" text DEFAULT '0-0-server' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"server_seq" bigint DEFAULT nextval('sync_seq') NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "workout_sets" ADD COLUMN "client_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
ALTER TABLE "workouts" ADD COLUMN "client_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "exercises_name_idx" ON "exercises" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "exercises_client_id_idx" ON "exercises" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "exercises_server_seq_idx" ON "exercises" USING btree ("server_seq");--> statement-breakpoint
CREATE UNIQUE INDEX "workout_sets_client_id_idx" ON "workout_sets" USING btree ("client_id");--> statement-breakpoint
CREATE UNIQUE INDEX "workouts_client_id_idx" ON "workouts" USING btree ("client_id");--> statement-breakpoint
-- Not generated by drizzle-kit: the sync sequence trigger is hand-written DDL that lives in
-- 0005 and has to be attached to every new syncable table. Without it `server_seq` is only set
-- by the column default, so an UPDATE never advances the cursor and the row's change never
-- reaches the phone — silently, and only for rows that are edited rather than created.
CREATE TRIGGER "exercises_bump_sync_seq" BEFORE INSERT OR UPDATE ON "exercises"
  FOR EACH ROW EXECUTE FUNCTION bump_sync_seq();
