CREATE TABLE "routine_exercises" (
	"id" serial PRIMARY KEY NOT NULL,
	"routine_id" integer NOT NULL,
	"exercise" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"target_sets" integer,
	"target_reps" integer,
	"target_weight_lbs" numeric(7, 2),
	"client_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"updated_hlc" text DEFAULT '0-0-server' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"server_seq" bigint DEFAULT nextval('sync_seq') NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "routines" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"client_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"updated_hlc" text DEFAULT '0-0-server' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"server_seq" bigint DEFAULT nextval('sync_seq') NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
DROP INDEX "exercises_name_idx";--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "name_key" text GENERATED ALWAYS AS (lower(btrim(name))) STORED;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "primary_muscles" text[] DEFAULT ARRAY[]::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "secondary_muscles" text[] DEFAULT ARRAY[]::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "primary_group" text;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "seed_key" text;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "user_edited_fields" text[] DEFAULT ARRAY[]::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "aliases" text[] DEFAULT ARRAY[]::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "how_to" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "notes" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "rest_seconds" integer;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "archived_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "seed_version" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "workout_sets" ADD COLUMN "completed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workout_sets" ADD COLUMN "notes" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "workout_sets" ADD COLUMN "piece_type" text;--> statement-breakpoint
ALTER TABLE "workouts" ADD COLUMN "exercise_notes" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "routine_exercises" ADD CONSTRAINT "routine_exercises_routine_id_routines_id_fk" FOREIGN KEY ("routine_id") REFERENCES "public"."routines"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "routine_exercises_routine_id_idx" ON "routine_exercises" USING btree ("routine_id");--> statement-breakpoint
CREATE UNIQUE INDEX "routine_exercises_client_id_idx" ON "routine_exercises" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "routine_exercises_server_seq_idx" ON "routine_exercises" USING btree ("server_seq");--> statement-breakpoint
CREATE UNIQUE INDEX "routines_client_id_idx" ON "routines" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "routines_server_seq_idx" ON "routines" USING btree ("server_seq");--> statement-breakpoint
CREATE INDEX "exercises_name_key_idx" ON "exercises" USING btree ("name_key");--> statement-breakpoint
CREATE UNIQUE INDEX "exercises_seed_key_idx" ON "exercises" USING btree ("seed_key");--> statement-breakpoint
CREATE INDEX "exercises_name_idx" ON "exercises" USING btree ("name");--> statement-breakpoint
-- Not generated by drizzle-kit: the sync sequence trigger is hand-written DDL that lives in
-- 0005 and has to be attached to every new syncable table. Without it `server_seq` is only set
-- by the column default, so an UPDATE never advances the cursor and the row's change never
-- reaches the phone — silently, and only for rows that are edited rather than created.
CREATE TRIGGER "routines_bump_sync_seq" BEFORE INSERT OR UPDATE ON "routines"
  FOR EACH ROW EXECUTE FUNCTION bump_sync_seq();
--> statement-breakpoint
CREATE TRIGGER "routine_exercises_bump_sync_seq" BEFORE INSERT OR UPDATE ON "routine_exercises"
  FOR EACH ROW EXECUTE FUNCTION bump_sync_seq();