/**
 * Generates `public/sw.js` from `src/lib/pwa/sw-template.js`, stamping in the commit it was
 * built from (V3 §1.1, D-146).
 *
 * The stamp is the whole point. A browser only re-installs a service worker when the script's
 * bytes differ from the copy it already has. Without a per-build stamp, any deploy that
 * changes app code but not the worker is invisible: `registration.update()` fetches an
 * identical file, fires nothing, and the installed app keeps running old JavaScript. Stamping
 * the commit makes every deploy a byte change, so "there is a new version" becomes a signal
 * the platform gives us for free instead of something we have to invent.
 *
 * Runs from `predev` and `prebuild`, so a generated worker always exists before either
 * `next dev` or `next build` looks for it. `public/sw.js` is gitignored.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(here, "..", "src", "lib", "pwa", "sw-template.js");
const target = path.join(here, "..", "public", "sw.js");

/**
 * Vercel sets the commit SHA for us. Locally, ask git. If neither answers — a tarball with no
 * `.git`, say — fall back to the clock, which is worse (it makes every build a "new version"
 * even when nothing changed) but is the safe direction to be wrong in: a spurious update
 * prompt is an annoyance, a missed one is an app running stale code for weeks.
 */
function buildId() {
  const fromVercel = process.env.VERCEL_GIT_COMMIT_SHA;
  if (fromVercel) return fromVercel.slice(0, 12);

  try {
    return execFileSync("git", ["rev-parse", "--short=12", "HEAD"], {
      cwd: here,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return `t${Date.now().toString(36)}`;
  }
}

const id = buildId();
const template = readFileSync(source, "utf8");

if (!template.includes("__BUILD_ID__")) {
  throw new Error("sw-template.js no longer contains __BUILD_ID__; the stamp would be a no-op");
}

const banner = `// GENERATED by scripts/build-sw.mjs from src/lib/pwa/sw-template.js — do not edit.\n`;
writeFileSync(target, banner + template.replaceAll("__BUILD_ID__", id), "utf8");

console.log(`  public/sw.js  build ${id}`);
