import { readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

/**
 * "No raw hex outside the token file" — DESIGN.md §2 rule 6, gated at last (V4 §1.12, D-202).
 *
 * This was the one item of §1.12 left `PENDING` after D-194, and the note beside it said why:
 * the rule could not land before the pass that removes the literals, or it would fail on the
 * day it was written. §1.6 and §1.10 were that pass, so it lands here.
 *
 * ## What the rule protects
 *
 * A component that names a colour cannot be themed. Five themes ship and a sixth costs one spec
 * in the generator plus one registry entry — but only for components that ask for colour by
 * role. One `#1e1018` in a card is a card that is the wrong colour in four themes, and nothing
 * about reading that line says so.
 *
 * ## What it deliberately does not catch
 *
 * Comments. Half the hex in this repo is documentation — `brand.ts` explains that the status bar
 * sat at `#0a161b` for two versions, `build-tokens.mts` records that `#09A1A1` is 2.94:1 on
 * paper. Those strings are the *evidence* for decisions and stripping them would make the
 * codebase worse. So comments are removed before scanning, in both JS and CSS syntax.
 *
 * It also does not catch `rgb()`, `hsl()` or a named colour like `black`. Those are worth adding
 * the day one appears; today none does, and a test that fails on nothing is a test whose
 * accuracy nobody has checked. §1.10 removed the one real instance — `bg-black/10` in the
 * vendored sheet — and the elevation tests in `tokens.test.ts` cover the place it is most
 * tempting to reintroduce.
 */

const ROOT = path.join(__dirname, "..", "..", "..", "..");
const SRC = path.join(ROOT, "src");

/**
 * Files allowed to contain a colour literal, each with the reason.
 *
 * A path is only in this list if the literal is *load-bearing* — something that genuinely cannot
 * be a custom property. "It would be annoying to change" is not a reason; every entry below
 * names a mechanism that rejects `var()`.
 */
const ALLOWED: Array<[relative: string, why: string]> = [
  [
    "app/tokens.css",
    "The token file itself. Generated by build-tokens.mts, and the hex in it is in trailing " +
      "comments beside each oklch() value so a reviewer can see the colour.",
  ],
  [
    "app/scale.css",
    "Generated by build-scale.mts. Holds no colour at all today; listed so that adding one is a " +
      "deliberate act rather than a test failure someone silences.",
  ],
  [
    "lib/theme/registry.ts",
    '`ground`, `accent` and `foreground` per theme. `<meta name="theme-color">` is markup and ' +
      "cannot read a custom property, so the value has to exist in JavaScript. tokens.test.ts " +
      "pins every one of them to the generated CSS, which is what makes the duplication safe.",
  ],
  [
    "lib/mark.ts",
    "The mark's luminance mask (D-346). `#fff` and `#000` here are not colours — they are the " +
      "keep and drop values of an SVG mask, where white preserves a pixel and black discards " +
      "it. Theming them is meaningless: a mask painted in `var(--primary)` would cut the folds " +
      "at whatever luminance that colour happens to have. The mark's actual colour is " +
      "`currentColor` and appears nowhere in this file.",
  ],
  [
    "components/site/mark.tsx",
    "The same mask, in JSX. See the entry for lib/mark.ts — the two are pinned together by " +
      "lib/__tests__/mark.test.ts, so the literals cannot diverge either.",
  ],
  [
    "components/site/filament-panel.tsx",
    'The fallback for `<input type="color">`, which accepts a 7-character hex string and ' +
      "nothing else — not a var(), not a colour function. It is also not a theme colour: it " +
      "stands in for the colour of a physical spool of filament.",
  ],
];

/** Regions inside a file that are exempt, for a reason as specific as the file-level ones. */
const ALLOWED_REGIONS: Array<[relative: string, from: RegExp, to: RegExp, why: string]> = [
  [
    "app/globals.css",
    /@media print/,
    /^\}/m,
    "The print stylesheet is frozen (V4 rule 5, Q123, Q355). Its colours are ink on paper — " +
      "black text, a grey rule — and are deliberately not themed: the deliverable is a PDF a " +
      "recruiter opens, and rasterising a dark theme onto A4 is how a resume stops being " +
      "machine-readable.",
  ],
];

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) return walk(full);
    return /\.(ts|tsx|css)$/.test(entry) ? [full] : [];
  });
}

/**
 * Blank out anything that is not a value, preserving line numbers.
 *
 * Replacing with spaces rather than deleting is what keeps the reported line number honest — a
 * failure that points at the wrong line is a failure someone spends ten minutes disbelieving.
 */
function blank(text: string): string {
  return text.replace(/[^\n]/g, " ");
}

function stripNonValues(source: string, isCss: boolean): string {
  let out = source.replace(/\/\*[\s\S]*?\*\//g, blank);
  if (!isCss)
    out = out.replace(/(^|[^:])\/\/[^\n]*/g, (m, lead) => lead + blank(m.slice(lead.length)));
  // `url(#fade-a1b2)` is an SVG fragment reference, and its id is often all hex characters.
  out = out.replace(/url\([^)]*\)/g, blank);
  return out;
}

/** 3, 4, 6 or 8 digits, and not the leading part of a longer identifier. */
const HEX = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})(?![0-9a-fA-F])/g;

type Finding = { file: string; line: number; literal: string };

function scan(): Finding[] {
  const allowedFiles = new Set(ALLOWED.map(([rel]) => rel));
  const findings: Finding[] = [];

  for (const full of walk(SRC)) {
    const rel = path.relative(SRC, full).split(path.sep).join("/");
    // Test files hold fixtures — a spool colour, an expected ground — and are not shipped.
    if (rel.includes("__tests__")) continue;
    if (allowedFiles.has(rel)) continue;

    let source = readFileSync(full, "utf8");
    for (const [region, from, to, ,] of ALLOWED_REGIONS) {
      if (region !== rel) continue;
      const start = source.search(from);
      if (start === -1) continue;
      const rest = source.slice(start);
      const end = rest.search(to);
      const stop = end === -1 ? source.length : start + end;
      source = source.slice(0, start) + blank(source.slice(start, stop)) + source.slice(stop);
    }

    const cleaned = stripNonValues(source, rel.endsWith(".css"));
    cleaned.split("\n").forEach((text, index) => {
      for (const match of text.matchAll(HEX)) {
        findings.push({ file: rel, line: index + 1, literal: match[0] });
      }
    });
  }
  return findings;
}

describe("no raw hex outside the token files", () => {
  it("finds no colour literal in a component", () => {
    const found = scan();
    const report = found.map((f) => `${f.file}:${f.line}  ${f.literal}`);
    expect(
      report,
      "A colour literal cannot be themed: it is one value in five themes. Take the colour from " +
        "a token, or — if the mechanism genuinely cannot accept var() — add the file to " +
        "ALLOWED in this test with the reason it cannot.",
    ).toEqual([]);
  });

  /**
   * The positive control.
   *
   * D-003's lesson, applied to a lint: a scanner that reports nothing is indistinguishable from
   * a scanner that is broken, and this one has three separate ways to silently match nothing —
   * the walk, the comment-stripping and the regex. So it is handed something it must catch.
   */
  it("catches a literal that is not in a comment", () => {
    const sample = ["const a = 1; // #ff0000 in a comment", 'const b = "#1e1018";'].join("\n");
    const cleaned = stripNonValues(sample, false);
    expect([...cleaned.matchAll(HEX)].map((m) => m[0])).toEqual(["#1e1018"]);
  });

  it("does not mistake an SVG fragment id for a colour", () => {
    // `#fade-a1` is four hex characters followed by a hyphen, which a naive \b regex matches.
    const cleaned = stripNonValues("stroke={`url(#fade-a1b2)`}", false);
    expect([...cleaned.matchAll(HEX)]).toEqual([]);
  });

  it("keeps the print block exempt and nothing else in globals.css", () => {
    // Guards the region-stripping: if the `to` pattern ever swallows the whole file, the print
    // exemption would silently exempt every rule above it too.
    const globals = readFileSync(path.join(SRC, "app", "globals.css"), "utf8");
    expect(globals).toMatch(/@media print/);
    const beforePrint = globals.slice(0, globals.search(/@media print/));
    expect([...stripNonValues(beforePrint, true).matchAll(HEX)]).toEqual([]);
  });

  it("documents a reason for every exemption", () => {
    for (const [rel, why] of ALLOWED) {
      expect(why.length, `${rel} is exempt without a reason`).toBeGreaterThan(40);
    }
    for (const [rel, , , why] of ALLOWED_REGIONS) {
      expect(why.length, `${rel} has a region exempt without a reason`).toBeGreaterThan(40);
    }
  });
});
