/**
 * Reading the degree audit into something a plan can be checked against (V3 §5.2, D-187).
 *
 * `context/01_engineering/degree_audit.md` is generated by `scripts/parse_dars.py` and is
 * markdown, not data — it was written to be *read*, and the planner is the first thing that
 * needs to compute with it. This parses that markdown rather than changing the generator,
 * deliberately: the file is regenerated from a fresh DARS audit whenever Victor saves one, and
 * a second format to keep in step would be a second thing to get wrong at exactly the moment
 * the first one changed.
 *
 * ## The shape it reads
 *
 *     ### GROUP HEADING
 *     - **REQUIREMENT NAME**
 *       - Needs: 8 COURSES            (or "4.0 UNITS 1 COURSE", or "12.0 UNITS 3 COURSES")
 *       - Select from: COM SCI 111 , 118 , M151B
 *       - Applied: COM SCI 131 (SP26, 4.00, B-)
 *
 * ## What it cannot know, and says so
 *
 * The GE lists run past two hundred courses and the generator truncates them with
 * `… and ~235 more (see the audit)`. A requirement carrying that marker has an **incomplete**
 * list, and `truncated` records it — so the planner can accept a course it cannot verify
 * instead of rejecting a valid one because the parser dropped it. Victor's call, and the right
 * way round: a checker that is wrong about what is allowed is worse than one that admits the
 * limits of what it was given.
 */

export type AppliedCourse = {
  course: string;
  term: string;
  units: number;
  grade: string;
};

export type Requirement = {
  /** Stable across regenerations: derived from the text, not from position. */
  id: string;
  group: string;
  name: string;
  /** How many courses are still needed, where the audit says so. */
  needsCourses: number | null;
  /** How many units are still needed, where the audit says so. */
  needsUnits: number | null;
  /** Course codes the audit names as acceptable. Possibly incomplete — see `truncated`. */
  selectFrom: string[];
  /** True when the audit's list was cut short by the generator. */
  truncated: boolean;
  /** What already counts toward it. */
  applied: AppliedCourse[];
};

/** Groups that are history or advice rather than something to plan around. */
const NOT_PLANNABLE = [
  "LATIN HONORS",
  "ADVANCED STANDING CREDIT",
  "AVAILABLE COURSES THAT MAY CONTRIBUTE",
];

function slug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

/**
 * Course codes out of one of the audit's `Select from:` lines.
 *
 * The lines are a department name followed by numbers, then another department, with commas
 * between numbers and nothing between departments — `COM SCI 111 , 118 , M151B EC ENGR 100`.
 * So the department is carried forward until a new one appears, which is what makes `118` mean
 * `COM SCI 118`.
 *
 * Ranges (`111 TO 187`) are kept verbatim as a single entry rather than expanded. Expanding
 * would invent course numbers that may not exist, and the planner treats a range as something
 * it cannot check — which is honest, and the same answer it gives for a truncated list.
 */
export function parseSelectFrom(line: string): { codes: string[]; truncated: boolean } {
  const truncated = /and\s+~?\d+\s+more/i.test(line);
  const text = line.replace(/,?\s*…?\s*and\s+~?\d+\s+more.*$/i, "");

  const codes: string[] = [];
  let department = "";
  let lastWasCourse = false;

  /**
   * A department word is letters only — `COM`, `SCI`, `EC`, `ENGR`, and the single letters in
   * `AN N EA`. Every course code carries a digit, so "letters only" separates the two cleanly.
   * Single letters have to be allowed or `AN N EA 10` loses its middle and becomes `AN EA 10`.
   */
  const isDepartmentWord = (token: string) => /^[A-Z&]+$/.test(token) && token !== "TO";

  for (const token of text.split(/\s*,\s*|\s+/).filter(Boolean)) {
    const bare = token.replace(/\([^)]*\)/g, "");

    if (isDepartmentWord(bare)) {
      // A department word straight after a course starts a *new* department. Without this,
      // `COM SCI 111 , 118 EC ENGR 100` produces `COM SCI EC ENGR 100` — the two departments
      // glued together, and every code after the join wrong.
      if (lastWasCourse) department = "";
      department = `${department} ${bare}`.trim();
      lastWasCourse = false;
      continue;
    }

    if (/^[A-Z]?[CM]?\d/i.test(bare) || bare === "TO") {
      if (bare === "TO") {
        // A range: fold it into the previous entry so `111 TO 187` stays one uncheckable thing.
        const previous = codes.pop();
        if (previous) codes.push(`${previous} TO`);
      } else {
        const last = codes[codes.length - 1];
        if (last?.endsWith(" TO")) codes[codes.length - 1] = `${last} ${bare}`;
        else codes.push(department === "" ? bare : `${department} ${bare}`);
      }
      lastWasCourse = true;
      continue;
    }

    // Anything else ends the current department, so a stray word cannot glue two together.
    department = "";
    lastWasCourse = false;
  }

  return { codes, truncated };
}

export function parseAudit(markdown: string): Requirement[] {
  const requirements: Requirement[] = [];
  let group = "";
  let current: Requirement | null = null;

  const commit = () => {
    if (!current) return;
    // Only what is still outstanding: a requirement with nothing left to need is history.
    if (current.needsCourses !== null || current.needsUnits !== null) requirements.push(current);
    current = null;
  };

  for (const raw of markdown.split(/\r?\n/)) {
    const line = raw.trimEnd();

    const heading = line.match(/^###\s+(.+)$/);
    if (heading) {
      commit();
      group = heading[1].trim();
      continue;
    }

    const named = line.match(/^-\s+\*\*(.+?)\*\*\s*$/);
    if (named) {
      commit();
      if (NOT_PLANNABLE.some((skip) => group.toUpperCase().includes(skip))) continue;
      const name = named[1].trim();
      current = {
        id: slug(`${group}-${name}`),
        group,
        name,
        needsCourses: null,
        needsUnits: null,
        selectFrom: [],
        truncated: false,
        applied: [],
      };
      continue;
    }

    if (!current) continue;

    const needs = line.match(/^\s+-\s+Needs:\s*(.+)$/);
    if (needs) {
      const units = needs[1].match(/([\d.]+)\s*UNITS?/i);
      const courses = needs[1].match(/(\d+)\s*COURSES?/i);
      if (units) current.needsUnits = Number(units[1]);
      if (courses) current.needsCourses = Number(courses[1]);
      continue;
    }

    const select = line.match(/^\s+-\s+Select from:\s*(.+)$/);
    if (select) {
      const parsed = parseSelectFrom(select[1]);
      current.selectFrom = parsed.codes;
      current.truncated = parsed.truncated;
      continue;
    }

    const applied = line.match(/^\s+-\s+Applied:\s*(.+?)\s*\(([^,]+),\s*([\d.]+),\s*([^)]+)\)/);
    if (applied) {
      current.applied.push({
        course: applied[1].trim(),
        term: applied[2].trim(),
        units: Number(applied[3]),
        grade: applied[4].trim(),
      });
    }
  }

  commit();
  return requirements;
}

/** Normalised for comparison: case and spacing vary between the audit and what gets typed. */
export function normaliseCourse(code: string): string {
  return code.toUpperCase().replace(/\s+/g, " ").trim();
}

/**
 * Whether a requirement's list names this course.
 *
 * Answers `null` — *cannot tell* — rather than `false` when the list was truncated or contains a
 * range, because those are the cases where the audit did not give us enough to say. The planner
 * shows that as an uncheckable match rather than as a rejection (Victor's call).
 */
export function listNames(requirement: Requirement, course: string): boolean | null {
  const wanted = normaliseCourse(course);
  if (requirement.selectFrom.some((code) => normaliseCourse(code) === wanted)) return true;
  if (requirement.truncated || requirement.selectFrom.some((code) => / TO /.test(code)))
    return null;
  return requirement.selectFrom.length === 0 ? null : false;
}
